title: T20 2024 WC Prediction Contest
email: your-email@example.com
description: Predict the outcomes of major sporting events
author: Ram Narasimhan
baseurl: "/prediction-contests"
url: "https://ram-n.github.io"

# Social Profiles

# Add your google-analytics ID here to activate google analytics
#google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
